account/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView

from account import views

from .forms import PwdResetConfirmForm, PwdResetForm

app_name = "account"

urlpatterns = [
    path("register/", views.RegisterUserView.as_view(), name="register"),
    path("login/", views.LogInUserView.as_view(), name="login"),
    path("logout/", views.LogOutUserView.as_view(), name="logout"),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    path('dashboard', login_required(TemplateView.as_view(
        template_name="account/user/dashboard.html")), name='dashboard'),
    path('profile', login_required(TemplateView.as_view(template_name="account/user/profile.html")), name='profile'),
    path('profile/edit/<int:pk>', views.UserProfileUpdate.as_view(), name='edit-profile'),
    path('profile/delete/<int:pk>', views.UserProfileDeleteView.as_view(), name='delete-profile'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                              success_url='password_reset_email_confirm',
                                              email_template_name='account/user/password_reset_email.html',
                                              form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                     success_url='/account/password_reset_complete/',
                                                     form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/password_reset_done.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/password_reset_complete.html"),
         name='password_reset_complete'),
]

cars/urls.py
from django.urls import path

from . import views

app_name = "cars"


urlpatterns = [
    path("", views.cars_all, name="cars_all"),
    path("car/<slug:slug>", views.car_detail, name="car_detail"),
    path("cars/location/<slug:location_slug>", views.cars_by_location, name="cars_by_location"),
    path("cars/make/<slug:make_slug>", views.cars_by_make, name="cars_by_make"),
    path("cars/add", views.add_car, name="add_car"),
    path("cars/image/add/<slug:car_slug>", views.add_car_image, name="add_car_image"),
    path("car/update/<slug:car_slug>", views.update_car, name="update_car"),
    path("car/delete/<slug:car_slug>", views.delete_car, name="delete_car")
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("cars.urls", namespace="cars")),
    path("appointment/", include("sales_appointment.urls", namespace="sales_appointment"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales_appointment/urls.py
from django.urls import path

from . import views

app_name = "sales_appointment"

urlpatterns = [
    path('', views.appointment_summary, name='appointment_summary'),
    path('add', views.appointment_add, name='appointment_add'),
    path('delete', views.appointment_delete, name='appointment_delete'),
    path('update', views.appointment_update, name='appointment_update'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.6.3.min.js"
    integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>
    {% block title %}
    {% endblock title %}
  </title>
  <style>
    .dropbtn {
      width: 5rem;
      padding: 10px;
      font-size: 16px;
      border: none;
    }

    .dropdown {
      position: relative;
      display: inline-block;
    }

    .dropdown-content {
      display: none;
      position: absolute;
      background-color: #f1f1f1;
      min-width: 160px;
      box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
      z-index: 1;
    }

    .dropdown-content a {
      color: blue;
      padding: 8px 10px;
      text-decoration: none;
      display: block;
      font-size: 20px;
      font-family: 'Times New Roman', Times, serif;
    }

    .dropdown-content a:hover {
      background-color: #ddd;
    }

    .dropdown:hover .dropdown-content {
      display: block;
    }

    .dropdown:hover .dropbtn {
      background-color: #3e8e41;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-spec">
    <div class="container-fluid">
      <div class="w-25 d-flex justify-content-start mx-3 d-flex justify-content-center">
        <div>
          {% load static %}
          <a href="{% url 'cars:cars_all' %}"><img class="logo-img" src="{% static '/logo/logo.png' %}"
              alt="My image"></a>
        </div>
      </div>
      <div class="w-40 navblock1 d-flex justify-content-center">
        <div>
          <a class="navbar-achor" href="#">BLOG</a>
        </div>
        <div>
          <a class="navbar-achor" href="#">CONTACT</a>
        </div>
        <div>
          <a class="navbar-achor" href="#">FAQ</a>
        </div>
      </div>
      <div class="w-30 navblock2 d-flex justify-content-center">
        {% if not user.is_authenticated %}
        <div>
          <a class="navbar-achor" href="{% url 'account:login' %}">LOGIN</a>
        </div>
        <div>
          <a class="navbar-achor" href="{% url 'account:register' %}">REGISTER</a>
        </div>
        {% else %}
        {% if request.session.is_staff %}
        <div class="dropdown">
          <div>
            {% load static %}
            <a href="#"><img class="logo-img" src="{% static '/logo/favicon.ico' %}" alt="My image"></a>
          </div>
          <div class="dropdown-content">
            <a href="{% url 'cars:add_car' %}">Add Car</a>
            <a href="#">Delete Car</a>
          </div>
        </div>
        {% else %}
        <div>
          <a type="button" role="button" href="{% url 'sales_appointment:appointment_summary' %}"
            class="btn btn-secondary">
            {% with total_appointment=appointment|length %}
            <div id="appointment-numbers" class="d-inline-flex">
              {% if total_appointment > 0 %}
              {{total_appointment}}
              {% else %}
              0
              {% endif %}
            </div>
            {% endwith %}
            <svg class="svg-icon"
              style="width: 2em; height: 2em;vertical-align: middle;fill: currentColor;overflow: hidden;"
              viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg">
              <path d="M810.666667 170.666667h-42.666667V106.666667a21.333333 21.333333 0 0 
        0-21.333333-21.333334h-42.666667a21.333333 21.333333 0 0 0-21.333333 
        21.333334V170.666667H341.333333V106.666667a21.333333 21.333333 0 0 
        0-21.333333-21.333334h-42.666667a21.333333 21.333333 0 0 0-21.333333 
        21.333334V170.666667H213.333333a85.333333 85.333333 0 0 0-85.333333 
        85.333333v554.666667a85.333333 85.333333 0 0 0 85.333333 85.333333h597.333334a85.333333 
        85.333333 0 0 0 85.333333-85.333333V256a85.333333 85.333333 0 0 0-85.333333-85.333333z m0 
        640H213.333333V341.333333h597.333334z m-358.826667-134.4a20.48 20.48 0 0 0 29.866667 
        0l181.333333-180.906667a21.76 21.76 0 0 0 0-30.293333l-23.04-22.613334a21.76 21.76 0 0 0-30.293333 
        0l-143.36 143.36-52.48-52.906666a21.76 21.76 0 0 0-30.293334 0l-22.613333 21.76a21.333333 21.333333 
        0 0 0 0 29.866666z" /></svg>
            Appointment
          </a>
        </div>
        <div class="dropdown">
          <div>
            <a type="button" role="button" href="{% url "account:dashboard" %}"
                        class="btn btn-outline-secondary border-0 basket-btn">
              <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                  class="bi bi-person" viewBox="0 0 16 16">
                  <path
                    d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                </svg>
                </div>
                <span class="fs15 fw500">Account</span>
            </a>
          </div>
          <div class="dropdown-content">
            <a type="button" class="btn p-1 btn-outline-primary" href="{% url "account:profile" %}">PROFILE</a>
            <a type="button" class="btn p-1 btn-outline-primary" href="{% url "account:edit-profile" pk=user.id %}">EDIT</a>
          </div>
        </div>
        <div class="dropdown-content">
          <a href="#">profile</a>
          <a href="#">update</a>
          <a href="#"></a>
        </div>
        {% endif %}
        <div>
          <a href="{% url 'account:logout' %}">LOGOUT</a>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>
  <div class="container">
    {% block search_content %}
    {% endblock %}
  </div>
  <div class="conatiner-fluid">
    {% block content %}
    {% endblock content %}
  </div>
</body>

</html>