cars/urls.py
from django.urls import path

from . import views

app_name = "cars"


urlpatterns = [
    path("", views.cars_all, name="cars_all"),
    path("car/<slug:slug>", views.car_detail, name="car_detail"),
    path("cars/location/<slug:location_slug>", views.cars_by_location, name="cars_by_location"),
    path("cars/make/<slug:make_slug>", views.cars_by_make, name="cars_by_make"),
    path("cars/add", views.add_car, name="add_car"),
    path("cars/image/add/<slug:car_slug>", views.add_car_image, name="add_car_image"),
    path("car/update/<slug:car_slug>", views.update_car, name="update_car"),
    path("car/delete/<slug:car_slug>", views.delete_car, name="delete_car")
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("cars.urls", namespace="cars")),
    path("appointment/", include("sales_appointment.urls", namespace="sales_appointment"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales_appointment/urls.py
from django.urls import path

from . import views

app_name = "sales_appointment"

urlpatterns = [
    path('', views.appointment_summary, name='appointment_summary'),
    path('add', views.appointment_add, name='appointment_add'),
    path('delete', views.appointment_delete, name='appointment_delete'),
    path('update', views.appointment_update, name='appointment_update'),
]

cars/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse

from account.models import AppUser

from .constant import LOCATION_CHOICE


class CarActiveInstockManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True, in_stock=True)


class Make(models.Model):
    brand = models.CharField(verbose_name="Brand Name", max_length=200, unique=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "makes"

    def __str__(self):
        return self.brand

    def get_absolute_url(self):
        return reverse("cars:cars_by_make", args=[self.slug])


class Model(models.Model):
    model = models.CharField(verbose_name="Car Model", max_length=150, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    make = models.ForeignKey(Make, on_delete=models.CASCADE, related_name="car_make")

    class Meta:
        verbose_name_plural = "models"

    def __str__(self):
        return self.model


class Location(models.Model):
    location = models.CharField(
        verbose_name="Show Room location",
        max_length=150,
        choices=LOCATION_CHOICE
    )
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "location"

    def __str__(self):
        return self.location

    def get_absolute_url(self):
        return reverse("cars:cars_by_location", args=[self.slug])


class Car(models.Model):
    user = models.ForeignKey(AppUser, on_delete=models.CASCADE, related_name="user")
    price = models.PositiveIntegerField(verbose_name="price")
    year_of_manufacture = models.CharField(verbose_name="year of manufacture", max_length=150)
    max_customization_price = models.PositiveIntegerField(verbose_name="Maximum amount for customization")
    description = models.TextField(verbose_name="Description", null=True, blank=True)
    make = models.ForeignKey(Make, on_delete=models.CASCADE, related_name="make", to_field="brand")
    model = models.OneToOneField(Model, on_delete=models.CASCADE, related_name="car_model", to_field="model")
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name="carlocation")
    slug = models.SlugField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    car_active_in_stock_objects = CarActiveInstockManager()

    class Meta:
        verbose_name_plural = "cars"
        ordering = ("-created", )

    def get_absolute_url(self):
        return reverse("cars:car_detail", args=[self.slug])

    def get_absolute_url_update(self):
        return reverse("cars:update_car", args=[self.slug])

    def get_car_image_absolute_url(self):
        return reverse("cars:add_car_image", args=[self.slug])

    def get_car_delete_absolute_url(self):
        return reverse("cars:delete_car", args=[self.slug])


class Feedback(models.Model):
    comment = models.TextField(verbose_name="Customer Comment")
    car = models.ForeignKey(Car,
                            on_delete=models.CASCADE,
                            verbose_name="car id")


class Rating(models.Model):
    star_ratings = models.SmallIntegerField(verbose_name="rating star",
                                            validators=(MinValueValidator(0), MaxValueValidator(5)))
    car = models.ForeignKey(Car,
                            on_delete=models.CASCADE,
                            verbose_name="car id")


class CarImage(models.Model):
    car_image = models.ImageField(upload_to="images/")
    car = models.ForeignKey(Car,
                            on_delete=models.CASCADE,
                            verbose_name="car id")

cars/forms.py
from django import forms

from .models import Car, CarImage


class CarForm(forms.ModelForm):
    class Meta:
        fields = ("price", "year_of_manufacture",
                  "max_customization_price", "description",
                  "make", "model",
                  "location")
        widgets = {
            'price': forms.NumberInput(attrs={'class': 'form-control w-50'}),
            'year_of_manufacture': forms.TextInput(attrs={'class': 'form-control w-50'}),
            'max_customization_price': forms.NumberInput(attrs={'class': 'form-control w-50'}),
            'description': forms.Textarea(attrs={'class': 'form-control w-50'}),
            'make': forms.Select(attrs={'class': 'form-control w-50'}),
            'model': forms.Select(attrs={'class': 'form-control w-50'}),
            'location': forms.Select(attrs={'class': 'form-control w-50'})
        }

        model = Car


class AddCarImageForm(forms.ModelForm):
    class Meta:
        fields = ("car_image",)
        widgets = {
            "car_image": forms.FileInput(attrs={'class': 'form-control w-50'})
            }
        model = CarImage

cars/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from auth.group_permission import group_required

from .forms import AddCarImageForm, CarForm
from .models import Car, CarImage, Location, Make, Model


def cars_all(request):
    cars = Car.car_active_in_stock_objects.all()
    for car in cars:
        car_images_list = CarImage.objects.all().filter(car=car.id).values()
        images = [(index, image["car_image"]) for index, image in enumerate(car_images_list)]
        car.images = images
    return render(request, "cars/home.html", {"cars": cars})


def car_detail(request, slug):
    car = get_object_or_404(Car, slug=slug, in_stock=True)
    car_images = CarImage.objects.all().filter(car=car.id).values()
    images = [image["car_image"] for image in car_images]
    return render(request, "cars/single.html", {"car": car, "images": images})


def cars_by_location(request, location_slug):
    location = get_object_or_404(Location, slug=location_slug)
    cars = Car.objects.filter(location=location)
    for car in cars:
        car_images_list = CarImage.objects.all().filter(car=car.id).values()
        images = [(index, image["car_image"]) for index, image in enumerate(car_images_list)]
        car.images = images
    return render(request, "cars/home.html", {"cars": cars})


def cars_by_make(request, make_slug):
    make = get_object_or_404(Make, slug=make_slug)
    cars = Car.objects.filter(make=make)
    for car in cars:
        car_image_list = CarImage.objects.all().filter(car=car.id).values()
        images = [(index, image["car_image"]) for index, image in enumerate(car_image_list)]
        car.images = images
    return render(request, "cars/home.html", {"cars": cars})


@group_required("Staff")
def add_car(request):
    template = "cars/addcar.html"
    addform = CarForm()
    if request.method == "POST":
        make = Make.objects.get(brand=request.POST.get("make"))
        model = Model.objects.get(model=request.POST.get("model"))
        location = Location.objects.get(id=request.POST.get("location"))
        car = Car(
            user=request.user,
            price=request.POST.get("price"),
            year_of_manufacture=request.POST.get("year_of_manufacture"),
            max_customization_price=request.POST.get("max_customization_price"),
            description=request.POST.get("description"),
            make=make,
            model=model,
            location=location,
            slug=make.slug+"-"+model.slug
        )
        car.save()
        return redirect(reverse("cars:add_car_image", args=[car.slug]))
    context = {"form": addform}
    return render(request, template, context)


@group_required("Staff")
def add_car_image(request, car_slug):
    template = "cars/addcarimage.html"
    car_img_form = AddCarImageForm()
    if request.method == "POST":
        car = Car.objects.get(slug=car_slug)
        form = AddCarImageForm(request.POST, request.FILES)
        if form.is_valid():
            car_image = form.save(commit=False)
            car_image.car = car
            car_image.save()
            return redirect("/")
    context = {"form": car_img_form}
    return render(request, template, context)


@group_required("Staff")
def update_car(request, car_slug):
    obj = get_object_or_404(Car, slug=car_slug)
    context = {}
    form = CarForm(request.POST or None, instance=obj)
    if request.method == "POST":
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect("/")
    context["form"] = form
    template = "cars/updatecar.html"
    return render(request, template, context)


@group_required("Staff")
def delete_car(request, car_slug):
    template = "cars/403.html"
    car = Car.objects.get(slug=car_slug)
    if request.user == car.user:
        car.delete()
    else:
        return render(request, template)
    return redirect("/")

templates/cars/addcar.html
{% extends 'base.html' %}
{% block title %}Add Car{% endblock title %}

{% block content %}
<div class="container">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1>Add Cars Page</h1>
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-10">
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/cars/addcarimage.html
{% extends 'base.html' %}
{% block title %}Add Car Image{% endblock title %}

{% block content %}
<div class="container">
    <div class="py-5">
        <div class="row">
            <div class="col-10">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/cars/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}
{% block search_content %}
{% load static %}
<div class="container-fluid" style="background-image: url('{% static "background/backgroundimage.jpeg"%}')";>
  <div class="row">
    <div class="col-3 m-3 p-3" style="height: 500px; z-index: 2;">
      <h5 class="mt-3">Find your right car</h5>
      <div class="dropdown">
        <button class="btn btn-primary mt-3">Search Car by Location</button>
        <div class="dropdown-content">
          {% for loc in locations %}
          <a href="{{ loc.get_absolute_url }}">{{ loc.location }}</a>
          {% endfor %}
        </div>
      </div>
      <div class="dropdown">
        <button class="btn btn-primary mt-3">Search Car by Brand</button>
        <div class="dropdown-content">
          {% for make in makes %}
          <a href="{{ make.get_absolute_url }}">{{ make.brand }}</a>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="col-5 mt-5 mx-5" style="color: aliceblue; 
          font-size: 25px; 
          font-family: 'Times New Roman', Times, serif;
          z-index: 5;">
      <span>
        let's find right car you.
      </span>
      <br>
      <span>
        Searching right car is always easy with us.
      </span>
    </div>
  </div>
</div>
{% endblock  %}
{% block content %}
<div class="container-fluid mt-3 mb-3">
  <div class="row">
    {% for car in  cars%}
    <div class="col-4">
      <a class="text-dark text-decoration-none" href="{{ car.get_absolute_url }}">
        <div class="card shadow-sm">
          <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              {% for image in car.images %}
              <div class="carousel-item {% if image.0 == 0 %}active{% endif %}">
                <img id="img-size" src="/media/{{image.1}}" class="d-block w-100" alt="main-image">
              </div>
              {% endfor %}
              {% for image in car.images %}
              {% if image.0 > 0 %}
              <div class="carousel-item">
                <img id="img-size" src="/media/{{image.1}}" class="d-block w-100" alt="alt-image">
              </div>
              {% endif %}
              {% endfor %}
            </div>
          </div>
          <div class="card-body">
            {% load mathfilters %}
            <p class="card-text">{{ car.make }} {{car.model}}</p>
            {% with  result=car.max_customization_price|add:car.price %}
            <p class="card-text">Rs {{ car.price|div:100000 }} to {{result|div:100000}} lakhs</p>
            {% endwith %}
            <p class="card-text">{{ car.location }}</p>
          </div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

templates/cars/single.html
{% extends '../base.html' %}
{% block title %}
{{ car.make }} {{car.model}}
{% endblock %}

{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="/media/{{images.0}}" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="/media/{{images.1}}" class="d-block w-100" alt="...">
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ car.make }}</h1>
                <p><span class="lead">{{ car.model }}</span></p>
                <p>{{ car.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <p>
                                    Price Range: {{car.price}} to {{car.price|add:car.max_customization_price}}
                                </p>
                                <p>Year of Manufacture: {{car.year_of_manufacture}}</p>
                                <p>Available at: {{car.location}}</p>
                            </div>
                            {% if not request.session.is_staff and request.session.user_email %}
                            <div class="d-flex justify-content-around">
                                <input class="col-6" type="date" name="appointment-date" id="appointment-date-id">
                                <button type="button" id="add-appointment" value="{{car.id}}"
                                    class="btn btn-primary btn-sm">Add to Appointment</button>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% if request.session.is_staff %}
                <button><a href="{{ car.get_car_image_absolute_url }}">Add More Image</a></button>
                {% endif %}
                {% if request.session.is_staff %}
                <button><a href="{{ car.get_absolute_url_update }}">Update Car</a></button>
                {% endif %}
                {% if request.session.is_staff %}
                <button><a href="{{ car.get_car_delete_absolute_url }}">Delete Car</a></button>
                {% endif %}
            </div>
        </div>
    </main>
</div>
<script>
    $(document).on('click', '#add-appointment', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "sales_appointment:appointment_add" %}',
            data: {
                carid: $('#add-appointment').val(),
                appointment_date: $('input[name=appointment-date]').val(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("appointment-numbers").innerHTML = json.appointment_number
            },
            error: function (xhr, errmsg, err) {}
        });
    });
</script>
{% endblock content %}

templates/cars/updatecar.html
{% extends 'base.html' %}
{% block title %}Update Car{% endblock title %}

{% block content %}
<div class="container">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-10">
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}